/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.66
 * Generated at: 2021-05-30 21:03:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class booking_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/navbar.jsp", Long.valueOf(1622408625563L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"UTF-8\" />\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("   \r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./static/style.css\" />\r\n");
      out.write("    <link rel=\"icon\" type=\"image/icon\" href=\"./static/images/icon.ico\" />\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    <header>\r\n");
      out.write("      <nav>\r\n");
      out.write("        <div class=\"navlink\">\r\n");
      out.write("          <ul>\r\n");
      out.write("            <li><a href=\"./index.jsp\">Home</a></li>\r\n");
      out.write("            <li><a href=\"#\">Hotels</a></li>\r\n");
      out.write("            <li><a href=\"#\">Services</a></li>\r\n");
      out.write("            <li><a href=\"./booking.jsp\">Book Now</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"signuplink\">\r\n");
      out.write("          <ul>\r\n");
      out.write("            <li><a href=\"./signup.jsp\">Signup</a></li>\r\n");
      out.write("            <li><a href=\"./login.jsp\">Login</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </nav>\r\n");
      out.write("    </header>\r\n");
      out.write("   </body>\r\n");
      out.write("</html>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"UTF-8\" />\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("    <title>Book Now</title>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("  ");

  response.setHeader("Cache-Control","no-cache, no-store, must-revalidate");//HTTP 1.1
  response.setHeader("Pragma","no-cache");// HTTP 1.0
  response.setHeader("Expires","0");//Proxies
  
  if(session.getAttribute("email")!=null){
	  response.sendRedirect("index.jsp");
  }
  
      out.write("\r\n");
      out.write("    <section class=\"main-page booking\">\r\n");
      out.write("      <section class=\"book-main\">\r\n");
      out.write("        <label for=\"\">Hotel</label>\r\n");
      out.write("        <select name=\"Hotel\" id=\"\">\r\n");
      out.write("          <option value=\"Hotel-1\">Hotel-1</option>\r\n");
      out.write("          <option value=\"Hotel-2\">Hotel-2</option>\r\n");
      out.write("          <option value=\"Hotel-3\">Hotel-3</option>\r\n");
      out.write("        </select>\r\n");
      out.write("        <br />\r\n");
      out.write("        <label for=\"\">Room Number</label>\r\n");
      out.write("        <select name=\"RoomNumber\" id=\"\">\r\n");
      out.write("          <option value=\"A1\">A1</option>\r\n");
      out.write("          <option value=\"B2\">B2</option>\r\n");
      out.write("          <option value=\"C3\">C3</option>\r\n");
      out.write("        </select>\r\n");
      out.write("        <br />\r\n");
      out.write("        <label for=\"\">Number of Guests</label>\r\n");
      out.write("        <select name=\"NoOfGuests\" id=\"\">\r\n");
      out.write("          <option value=\"1\">1</option>\r\n");
      out.write("          <option value=\"2\">2</option>\r\n");
      out.write("          <option value=\"3\">3</option>\r\n");
      out.write("        </select>\r\n");
      out.write("        <br />\r\n");
      out.write("        <label for=\"\">Checkin Date: </label>\r\n");
      out.write("        <input type=\"date\" id=\"\" name=\"CinDate\" /><br />\r\n");
      out.write("        <label for=\"\">Checkout Date: </label>\r\n");
      out.write("        <input type=\"date\" id=\"\" name=\"CoutDate\" /><br />\r\n");
      out.write("      </section>\r\n");
      out.write("      <h2>Quick Services</h2>\r\n");
      out.write("      <section class=\"general-SBH\">\r\n");
      out.write("        <div class=\"general-SBHbox addS1\">\r\n");
      out.write("          <button>Add Service</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"general-SBHbox assS2\">\r\n");
      out.write("          <button>Add Service</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"general-SBHbox addS3\">\r\n");
      out.write("          <button>Add Service</button>\r\n");
      out.write("        </div>\r\n");
      out.write("      </section>\r\n");
      out.write("      <input type=\"submit\" value=\"Book Now\" />\r\n");
      out.write("    </section>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
